version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: credit_approval
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
    environment:
      - DJANGO_SETTINGS_MODULE=credit_approval.settings
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - DJANGO_SUPERUSER_EMAIL=admin@gmail.com

  celery:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    command: celery -A credit_approval worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_started
    environment:
      - DJANGO_SETTINGS_MODULE=credit_approval.settings

volumes:
  postgres_data: